sudo: required
services:
  - docker

before_install:
  - docker build --file Dockerfile.dev --tag debugme/docker-react .

script:
  - docker run debugme/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: docker-react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-eu-west-2-417603968335
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY